### ISSUE TITLE
Add railsbridge logo to navbar

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#12]
The navbar brand and intro "RailsBridge SD" should be logos instead of text

![screen shot 2017-03-26 at 1 32 14 pm](https://cloud.githubusercontent.com/assets/20118615/24334926/aa48051c-1228-11e7-969e-63948a3bc463.png)
![screen shot 2017-03-26 at 1 32 11 pm](https://cloud.githubusercontent.com/assets/20118615/24334928/ab6f0ef4-1228-11e7-9335-d0a6fd8850de.png)

**Comment by mokolabs** [comment]
FYI... I just added a logo to the navar with this commit: 776014dc6c8db5f892e26bd8a7f3cc0c33f8b46d

**Comment by mokolabs** [comment]
We may not need the logo in the `#intro` section, so I'm closing this for now.

We can always add it back as a new issue later.
