### ISSUE TITLE
Fix visibility of navbar links against background image

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#14]
We need to decide how we want to make the navbar links more visible. We can either edit (or change) the photo or edit the text... or both depending on the look we want.

![screen shot 2017-03-26 at 1 34 31 pm](https://cloud.githubusercontent.com/assets/20118615/24334953/01ff2268-1229-11e7-8407-fcb75ad498c0.png)

**Comment by mokolabs** [comment]
We could also try adding a dark transparent background behind the text.

**Comment by sslampa** [comment]
![selection_010](https://cloud.githubusercontent.com/assets/11300367/24367556/e43ac58a-12d1-11e7-8a27-357a66f2a211.png)

What do you guys think about that?

**Comment by stephchin** [comment]
Too dark... try some colors from our color palette.

**Comment by sslampa** [comment]
![selection_011](https://cloud.githubusercontent.com/assets/11300367/24368301/bf7607a2-12d4-11e7-98d0-8120f0051daf.png)

![selection_012](https://cloud.githubusercontent.com/assets/11300367/24368306/c51a443e-12d4-11e7-89e7-93d57f793236.png)

![selection_013](https://cloud.githubusercontent.com/assets/11300367/24368309/c87a2090-12d4-11e7-975d-4720471a45b6.png)

**Comment by sslampa** [comment]
Sorry I keep flooding this, but here's another one
![selection_014](https://cloud.githubusercontent.com/assets/11300367/24368545/abc34f0c-12d5-11e7-91c1-57d87e87a446.png)

**Comment by mokolabs** [comment]
So far, I like the red the most because the text is the easiest to read with that color.

We could also think about using the same transparent background color with our headline text, though this will be tricky to do with CSS.

**Comment by sslampa** [comment]
Yea, I like the red the most. The alpha level is at .75 right now, so if we think that's still too dark it can easily be changed. Is the headline text the text with a background color on the picture?

**Comment by mokolabs** [comment]
Basically, yeah. The H1 and H2 text inside of #intro.

```html
<div class='intro-content text-center'>
  <h1>RailsBridge San Diego</h1>
  <h2>RailsBridge is a day and a half FREE workshop</h2>
  <br>
  <h2>that will take students through building</h2>
  <br>
  <h2>a complete web application using Ruby on Rails.</h2>
  <p><a href=https://www.bridgetroll.org/events/342 class="btn btn-primary" >Sign Up</a></p>
</div>
```

BTW, there should only be one H2 tag inside `#intro`. We should remove the hard-coded line breaks because they won't look right on smaller screens.

Let's force line breaks by making a style which shrinks the width of the H2 tag on `#intro` -- which will force the text to wrap as we desire.

**Comment by mokolabs** [comment]
Nice work, @sslampa.

So I think the transparent red color looks the best, but I'm still concerned about legibility. It's still slightly hard to reach the navbar text -- which we don't want.

Let's try using our peach color (with no transparency) on the navbar. I think that's probably better.

(We'll keep experimenting and tweaking with the look of the site until we make it super awesome.)

**Comment by mokolabs** [comment]
I also set the RailsBridge text in the navar to bold so it stands out more.

**Comment by mokolabs** [comment]
<img width="1153" alt="screen shot 2017-03-27 at 12 45 04 pm" src="https://cloud.githubusercontent.com/assets/444/24374862/3a896694-12eb-11e7-9de2-32a3c02df2d8.png">

**Comment by mokolabs** [comment]
I'm closing this for now (but I will open a separate issue for fixing the H1 and H2 text in #intro).
