### ISSUE TITLE
Link navbar curriculum to curriculum section

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#18]
I think it might be helpful to have a section that explains what the curriculum is, but we could also just link straight to the curriculum in the navbar and remove the section for it.

**Comment by mokolabs** [comment]
Yeah, let's keep those navbar links always pointing to content on our actual site. By doing so, we will make a nicer and more consistent experience for users.

So let's add a curriculum section with a matching navbar link first, and then we can also link to the real curriculum site at the bottom of that section after we've explained the basics.

**Comment by mokolabs** [comment]
I'm closing this.
