### ISSUE TITLE
Add mailing list signup form

### ISSUE THREAD

**Issue by mokolabs** [railsbridgesd/railsbridgesd#25]
Also... we're going to need a place where people can sign up for our newsletter.

When we have a scheduled RailsBridge listed on the site, we'll just point folks to our Bridgetroll page so they can sign up for the event directly.

But when we DON'T have any upcoming events, we will let people sign up for our mailing list right on the RailsBridge San Diego site.

To do this, we'll need:

- [x] Signup form with email field and signup button
- [x] Create free MailChimp account for RailsBridge San Diego
- [x] Set up API keys for MailChimp account
- [x] Integration with MailChimp (so we can save emails to our mailing list)
- [x] Show/hide mailing list signup based on whether there is an event soon
- [x] Show/hide schedule based on whether there is an event soon

**Comment by stephchin** [comment]
I'm going to start working on the form and show/hide functionality. Will probably need to leave the mailchimp stuff for you.

**Comment by mokolabs** [comment]
👍

**Comment by mokolabs** [comment]
Okay, this is done!

- Added gibbon gem
- Updated README with Mailchimp .env variables
- Added descriptions for all .env variables in README
- Renamed :subscriberEmail param to just :email
- Used #strip method to remove whitespace from newsletter emails
- Added support for showing mailing list signup form by adding ?list=show param
- Updated subscribe action to add email to MailChimp list (via gibbon gem)
