### ISSUE TITLE
Add real text to all content sections

### ISSUE THREAD

**Issue by mokolabs** [railsbridgesd/railsbridgesd#30]
We need text for the following sections:

- [x] About
- [x] FAQ
- [x] Schedule
- [x] Curriculum
- [x] Code of Conduct
- [x] Volunteer
- [x] Resources

Let's try to see if we can copy text from our Bridgetroll page first, and then we can tweak and/or add anything else we may need.

**Comment by stephchin** [comment]
Adding some content from the RailsBridge site, definitely need to read through and tweak after.

**Comment by mokolabs** [comment]
Okay, sweet. Love the new fonts!

I'll ask Lisa to work on the copy for us.

**Comment by mokolabs** [comment]
This is done! Go team!
