### ISSUE TITLE
Update contact form email to load credentials from a secrets file

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#34]
When we send email using the contact form, it's sent via Gmail API with the Pony gem, but we definitely don't want to save anyone's username and password in this repo... so we need to update the contact form (and the whole app) to support loading secrets from a standard `.env` file in development and from Heroku config variables in production (since the site will be hosted on Heroku).

**Comment by mokolabs** [comment]
Is this issue still active? What our the next steps on this?

(I know we might discussed it on Slack, but it's good to keep the issue current.)

**Comment by stephchin** [comment]
Yes still active... this needs to be updated with the RailsBridgeSD gmail password (or app secret). We also need to configure the domain once it goes live on heroku.

**Comment by mokolabs** [comment]
Okay, this is done now.

You guys should definitely look at this code and see how it works. Using a `.env` file to store account secrets is a pretty common workflow for Ruby developers.
