### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by mokolabs** [railsbridgesd/railsbridgesd#36]
We need to add a button people can use to donate money to RailsBridge San Diego.

The donation will be processed via PayPal, so we'll need account info for that. (I'll ask Lisa for it.)

**Comment by sslampa** [comment]
I looked into this. It's supposed to be really simple, once we have access to the account, it's a matter of copy and pasting the given form. We can style it from there.

**Comment by mokolabs** [comment]
Okay, great. I'll get the account credentials from Lisa tomorrow.

**Comment by mokolabs** [comment]
This is done.

Unfortunately, the button is pretty ugly. And, for security reasons, we can't change it easily -- even if we had access to the main RailsBridge PayPal account (which we don't).

So I opted for just putting it at the bottom of the About section.

If you think of a better solution, let me know. But I think we can close this issue for now.
