### ISSUE TITLE
Fix navbar responsiveness

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#49]
![screen shot 2017-03-28 at 3 50 14 pm](https://cloud.githubusercontent.com/assets/20118615/24431245/a1fdb8fe-13cf-11e7-9546-2f0e72a07643.png)

**Comment by mokolabs** [comment]
There's definitely more to do here, but this is a good start!

**Comment by mokolabs** [comment]
Haha. Well, actually, I'm not sure if this screenshot is a before or after.

But, either way, I'm thinking we should hold off on the responsive stuff until we finish the rest of the site. That way, we will only have to make responsive tweaks once.

**Comment by mokolabs** [comment]
I'm closing this issue, but will reopen it or make a new ticket when we do responsive support.
