### ISSUE TITLE
Add responsive support

### ISSUE THREAD

**Issue by mokolabs** [railsbridgesd/railsbridgesd#69]
We need to make sure the site looks great on smaller screens.

Let's use this issue to keep a running list of things we need to fix. If you find something, add it to the list and then submit a commit that fixes it.

- [x] Resize #header height on page load (not just resize)
- [x] Hide carousel controls on iPhone 7/6 and below
- [x] Push header image below navbar on iPad and below
- [x] Shrink Twitter widget to fit on small screens
- [x] Increase left margin on railsbridge icon in header
- [x] Remove #intro headline text wrap on smaller screens
- [x] Tweak navbar toggle colors on peach/non-scrolled navbar
- [x] Tweak navbar toggle colors on white/scrolled navbar
- [x] Decrease H1 size on iPhone 7/6 and below
- [x] Decrease H2 size on iPhone 7/6 and below
- [x] Decrease left and right padding on .schedule-block on iPhone 7/6 Plus and below
- [x] Fix clipped 'get involved' question text on iPhone SE/5s/5
- [x] Set width of Twitter widget to 100% at 768px and below
- [x] Tweak right padding on footer on iPad only
- [x] Left align mobile nav links on small screens
- [x] Show all nav links in dropdown menu on small screens
- [x] Restyle navbar when wrapped to second line
- [x] Fix issues with sponsors slideshow on smaller screens (aka "revenge of the whitespace!")
- [x] Hide slideshow controls on small screens
- [x] Tweak sponsor block height and image margins at 1200px or wider
- [x] Fix issues with sponsors slideshow on smaller screens (again)
- [x] Decrease #intro headline top margin on iPad Pro and smaller

To find more issues, switch to responsive mode using the dev tools in Chrome, load the site up and then try looking closely at the site at different screen sizes. Eventually, you'll start to see little tiny bugs or things we could tweak to improve the mobile experience.

**Comment by mokolabs** [comment]
Also, I'm not sure how much responsive stuff you guys have done so far.

The general workflow I'm using for this site is desktop-first. NOT mobile-first. So... we make sure everything looks awesome on the desktop (which we've done) and then we go back and make it all look great on mobile.

Using the Chrome dev tools, we can preview how the site looks on different mobile devices.

So, let's start by getting everything looking great for the iPad (using a `max-width` 768px breakpoint), and then we'll move down to the next biggest device. By using `max-width`, our changes will apply to all devices with the same or smaller screen width.

It's already looking pretty good, so we shouldn't have to do too much work. But let's aim for fixing any serious issues on iPad, iPhone 7/6 Plus, iPhone 7/6, and iPhone 5/5s/SE.

**Comment by mokolabs** [comment]
I'm going to be working on this stuff in the morning. We should make sure the site looks great on all mobile devices!

**Comment by stephchin** [comment]
Ok! I should have time tomorrow too. I'll check in with you before I start.

**Comment by mokolabs** [comment]
Sweet. Thanks!

**Comment by stephchin** [comment]
I'll work on the last one (Fix issues with sponsors slideshow on smaller screens...)

**Comment by mokolabs** [comment]
Okay... I think we're done with all of the critical responsive fixes, so I'm closing this.

If you see anything else, just open a new issue.

Thanks, guys!
